os:
- Visual Studio 2017
environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      TRIPLET: x64-windows
      CMAKE_OPTS: "-DBUILD_SHARED_LIBS=off"
      TESTS: ON
    - GENERATOR: "Visual Studio 15 2017"
      TRIPLET: x86-windows
      CMAKE_OPTS: "-DBUILD_SHARED_LIBS=off"
      TESTS: ON
    - GENERATOR: "Visual Studio 15 2017 ARM"
      TRIPLET: arm-windows
      CMAKE_OPTS: "-DENABLE_OPENSSL=off"
    - GENERATOR: "Visual Studio 15 2017"
      TRIPLET: x86-uwp
      CMAKE_OPTS: "-DCMAKE_SYSTEM_NAME=WindowsStore"
      TESTS: ON
    - GENERATOR: "Visual Studio 15 2017 Win64"
      TRIPLET: x64-uwp
      CMAKE_OPTS: "-DCMAKE_SYSTEM_NAME=WindowsStore"
      TESTS: ON
    - GENERATOR: "Visual Studio 15 2017 ARM"
      TRIPLET: arm-uwp
      CMAKE_OPTS: "-DCMAKE_SYSTEM_NAME=WindowsStore -DENABLE_OPENSSL=off"
    - GENERATOR: "Visual Studio 15 2017"
      TRIPLET: arm64-windows
      CMAKE_OPTS: "-AARM64 -DENABLE_OPENSSL=off"
    - GENERATOR: "Visual Studio 15 2017"
      TRIPLET: arm64-uwp
      CMAKE_OPTS: "-AARM64 -DCMAKE_SYSTEM_NAME=WindowsStore -DENABLE_OPENSSL=off"
cache:
  - C:\cache
before_build:
  cmd: >-
    if NOT EXIST C:\cache ( mkdir C:\cache )

    git clone https://github.com/Microsoft/vcpkg

    xcopy C:\cache\* vcpkg\downloads /Y /I /F

    cd vcpkg

    .\bootstrap-vcpkg.bat

    .\vcpkg integrate install

    .\vcpkg install zlib:%TRIPLET% bzip2:%TRIPLET%

    cd ..

    xcopy vcpkg\downloads\*.zip C:\cache /Y /I /F

    mkdir build

    cd build

    cmake -DCMAKE_TOOLCHAIN_FILE=%cd%/../vcpkg/scripts/buildsystems/vcpkg.cmake .. -G "%GENERATOR%" %CMAKE_OPTS%

    appveyor PushArtifact config.h

    appveyor PushArtifact CMakeCache.txt

build_script:
  cmd: >-
    cmake --build . --config Release --target INSTALL

    cmake --build . --config Debug --target INSTALL
