os:
- Visual Studio 2017
before_build:
  cmd: >-
    vcpkg install zlib:x64-windows

    mkdir build

    cd build

    cmake .. -G"Visual Studio 15 2017 Win64"

#build_script:
#  cmake --build . --config Release --target INSTALL
