version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    vcpkg update

    cd C:\Tools\vcpkg

    git fetch https://github.com/janisozaur/vcpkg libzip

    git checkout FETCH_HEAD

    .\bootstrap-vcpkg.bat

    .\vcpkg integrate install

    echo updated

    echo D | xcopy C:\projects\libzip-1\* C:\Tools\vcpkg\buildtrees\libzip\

    vcpkg install libzip
on_failure:
- cmd: >-
    type C:\Tools\vcpkg\buildtrees\libzip\install-x86-windows-rel-out.log

    type C:\Tools\vcpkg\buildtrees\libzip\install-x86-windows-rel-err.log
